version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: train_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: traindb
      MYSQL_USER: train
      MYSQL_PASSWORD: train
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpw"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  mysql_data: